version: '3'

networks:
  inception:
    name: inception
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/user42/data/wordpress
      o: bind
  mariadb-v:
    driver: local
    driver_opts:
      type: none
      device: /home/user42/data/mariadb
      o: bind

services:
#  mariadb:
#    container_name: mariadb
#    networks:
#      - inception
#    build:
#      context: requirements/mariadb
#      dockerfile: Dockerfile
#    volumes:
#      - mariadb:/var/lib/mysql
#    restart: unless-stopped
#    expose:
#      - 3306
#    env_file: .env
#    environment:
#        - DB_NAME=${DB_NAME}
#        - DB_USER=${DB_USER}
#        - DB_PASSWORD=${DB_PASSWORD}
  mariadb:
      build:
        context: ./requirements/mariadb/
        args:
          - DB_NAME=${DB_NAME}
          - DB_USER=${DB_USER}
          - DB_PASSWORD=${DB_PASSWORD}
      image: mariadb:inception
      container_name: mariadb
      restart: on-failure
      healthcheck:
        test: mysqladmin ping -h localhost -u root
        interval: 3s
        timeout: 3s
        retries: 5
      volumes:
        - mariadb-v:/var/lib/mysql
      networks:
        - inception
      env_file: .env
      environment:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file: .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    ports:
      - 443:443
    restart: on-failure

  wordpress:
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    depends_on:
        - mariadb
    restart: on-failure
    expose:
      - 9000
    env_file: .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - WP_ROOT_USER
      - WP_ROOT_EMAIL
      - WP_ROOT_PASSWORD
      - WP_USER
      - WP_EMAIL
      - WP_PASSWORD